add tensorrt fp32 conversion :sparkles:
BlueMirrors/cvu pull request #22
Opened 2022-02-03 13:01 UTC by makaveli10

cvu now supports YOLOv5 TensorRT FP32 conversion

2022-02-03 20:07 UTC, shivamswarnkar commented on cvu/detector/yolov5/core.py
> +    def _load_model(self, backend_name: str, weight: str, device: str, **kwargs) -> None:
same ```type-hint``` discussion applies here

2022-02-03 20:08 UTC, shivamswarnkar requested changes

2022-02-03 20:08 UTC, shivamswarnkar commented on cvu/detector/yolov5/backends/yolov5_tensorrt.py
> +                 fp16: bool = False) -> None:
shouldn't default be True? Assuming most people would prefer ```fp16``` vs ```fp32```?

2022-02-04 04:18 UTC, ankitnamdeo34 commented on cvu/detector/yolov5/backends/yolov5_tensorrt.py
> +                 fp16: bool = False) -> None:
As per me default should be 32 for better precision to avoid underflow and overflow for better compatibility and generic use case but again based on research which nvidia does most weights and gradients tend to fall well within the 16-bit representable range and when they not then  scaling up the gradient was sufficient to achieve convergence. But seeing current advancement in GPU and CPU fp32 can be used but the comparison is between precision vs speed, fp16 is twice as much faster as fp32.

2022-02-04 05:25 UTC, ankitnamdeo34 commented on cvu/detector/yolov5/core.py
> +                 **kwargs) -> None:
nice suggestion, None can also be replaced with NoReturn

2022-02-04 05:27 UTC, ankitnamdeo34 approved these changes
looks good to me, we  need to think about shivams type-hints suggestion for future release

2022-02-04 10:32 UTC, makaveli10 commented on cvu/detector/yolov5/core.py
> +                 **kwargs) -> None:
Yeah, sounds good.

2022-02-04 10:33 UTC, makaveli10 commented on cvu/detector/yolov5/backends/yolov5_tensorrt.py
> +                 fp16: bool = False) -> None:
In most of the cases, I didnt see any performance drop with FP16 so lets default to fp16 true

2022-02-04 21:05 UTC, shivamswarnkar commented on cvu/detector/yolov5/backends/yolov5_tensorrt.py
> +                 fp16: bool = False) -> None:
@ankitnamdeo34 You have a good point, and @makaveli10 you're also correct. Maybe we can find a better way in between, i.e. replace ```float16``` param with ```dtype```. We can have a detailed discussion on what default type value we should go with. And this will be a nice way to provide ```int8``` and other type options later on. However, this will require large changes (basically updating every backend), so how about we do it in the next release? 

As for this current case, I think keeping the existing behavior is probably the best idea, given we already have some users, and adding new args/params shouldn't require changes in their codebase. 

What do you guys think?

2022-02-04 21:08 UTC, shivamswarnkar approved these changes

2022-02-05 03:57 UTC, ankitnamdeo34 approved these changes

2022-02-05 16:53 UTC, merged